import type { ServiceDefinition } from '../../packages/contracts/src';

export type ServiceTone = 'mint' | 'sky' | 'peach' | 'lemon';
export type ServiceGlyph = 'chat' | 'return' | 'bolt' | 'sparkles';

export interface AdminServiceDefinition extends ServiceDefinition {
  category: string;
  tone: ServiceTone;
  glyph: ServiceGlyph;
}

const sharedBookingWindow = {
  minimumNoticeMinutes: 120,
  maximumAdvanceDays: 90,
  cancellationNoticeMinutes: 24 * 60,
  rescheduleNoticeMinutes: 12 * 60,
};

export const INITIAL_ADMIN_SERVICES: readonly AdminServiceDefinition[] = [
  {
    id: 'service-consultation',
    organizationId: 'sea-and-kin',
    locationIds: ['studio-a', 'studio-b'],
    name: 'First-time consultation',
    slug: 'first-time-consultation',
    shortDescription: 'A thoughtful first visit to understand your goals and make a clear plan.',
    category: 'Consultations',
    tone: 'mint',
    glyph: 'chat',
    duration: {
      defaultMinutes: 60,
      minimumMinutes: 30,
      maximumMinutes: 120,
      incrementMinutes: 15,
    },
    buffers: { beforeMinutes: 10, afterMinutes: 10 },
    bookingWindow: { ...sharedBookingWindow },
    priceMinor: 9500,
    currency: 'USD',
    deposit: { mode: 'none', currency: 'USD', refundable: true },
    confirmationMode: 'automatic',
    changeApprovalMode: 'business',
    capacity: 1,
    staffIds: ['staff-mara', 'staff-noah'],
    resourceIds: [],
    customQuestions: [],
    isActive: true,
    isPublic: true,
    version: 1,
  },
  {
    id: 'service-follow-up',
    organizationId: 'sea-and-kin',
    locationIds: ['studio-a', 'studio-b'],
    name: 'Follow-up session',
    slug: 'follow-up-session',
    shortDescription: 'Focused time to continue the work and keep momentum moving.',
    category: 'Ongoing care',
    tone: 'sky',
    glyph: 'return',
    duration: {
      defaultMinutes: 45,
      minimumMinutes: 30,
      maximumMinutes: 90,
      incrementMinutes: 15,
    },
    buffers: { beforeMinutes: 5, afterMinutes: 10 },
    bookingWindow: { ...sharedBookingWindow, minimumNoticeMinutes: 60 },
    priceMinor: 7500,
    currency: 'USD',
    deposit: { mode: 'none', currency: 'USD', refundable: true },
    confirmationMode: 'automatic',
    changeApprovalMode: 'affected_staff',
    capacity: 1,
    staffIds: ['staff-mara', 'staff-noah', 'staff-lei'],
    resourceIds: [],
    customQuestions: [],
    isActive: true,
    isPublic: true,
    version: 1,
  },
  {
    id: 'service-quick-check-in',
    organizationId: 'sea-and-kin',
    locationIds: ['studio-a'],
    name: 'Quick check-in',
    slug: 'quick-check-in',
    shortDescription: 'A short, practical appointment for one clear question or adjustment.',
    category: 'Ongoing care',
    tone: 'lemon',
    glyph: 'bolt',
    duration: {
      defaultMinutes: 30,
      minimumMinutes: 15,
      maximumMinutes: 45,
      incrementMinutes: 15,
    },
    buffers: { beforeMinutes: 5, afterMinutes: 5 },
    bookingWindow: { ...sharedBookingWindow, minimumNoticeMinutes: 30, maximumAdvanceDays: 45 },
    priceMinor: 4500,
    currency: 'USD',
    deposit: { mode: 'none', currency: 'USD', refundable: true },
    confirmationMode: 'automatic',
    changeApprovalMode: 'automatic',
    capacity: 1,
    staffIds: ['staff-lei'],
    resourceIds: [],
    customQuestions: [],
    isActive: true,
    isPublic: true,
    version: 1,
  },
  {
    id: 'service-extended',
    organizationId: 'sea-and-kin',
    locationIds: ['studio-a'],
    name: 'Extended service',
    slug: 'extended-service',
    shortDescription: 'Extra room for a more involved session without feeling rushed.',
    category: 'Specialty',
    tone: 'peach',
    glyph: 'sparkles',
    duration: {
      defaultMinutes: 90,
      minimumMinutes: 60,
      maximumMinutes: 180,
      incrementMinutes: 30,
    },
    buffers: { beforeMinutes: 15, afterMinutes: 20 },
    bookingWindow: { ...sharedBookingWindow, minimumNoticeMinutes: 24 * 60 },
    priceMinor: 14500,
    currency: 'USD',
    deposit: {
      mode: 'fixed',
      currency: 'USD',
      fixedAmountMinor: 2500,
      refundable: true,
    },
    confirmationMode: 'manual',
    changeApprovalMode: 'business_and_affected_staff',
    capacity: 1,
    staffIds: ['staff-mara', 'staff-lei'],
    resourceIds: [],
    customQuestions: [],
    isActive: true,
    isPublic: true,
    version: 1,
  },
];
